// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldIsPrivate holds the string denoting the is_private field in the database.
	FieldIsPrivate = "is_private"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldFollower holds the string denoting the follower field in the database.
	FieldFollower = "follower"
	// FieldFollowing holds the string denoting the following field in the database.
	FieldFollowing = "following"
	// FieldPhotoDir holds the string denoting the photo_dir field in the database.
	FieldPhotoDir = "photo_dir"
	// Table holds the table name of the account in the database.
	Table = "accounts"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldOwner,
	FieldIsPrivate,
	FieldCreatedAt,
	FieldFollower,
	FieldFollowing,
	FieldPhotoDir,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	OwnerValidator func(string) error
	// DefaultIsPrivate holds the default value on creation for the "is_private" field.
	DefaultIsPrivate bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultFollower holds the default value on creation for the "follower" field.
	DefaultFollower int64
	// DefaultFollowing holds the default value on creation for the "following" field.
	DefaultFollowing int64
	// PhotoDirValidator is a validator for the "photo_dir" field. It is called by the builders before save.
	PhotoDirValidator func(string) error
)
