version: '3'
services:
  db:
    image: postgres:latest
    container_name: project
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: project
    ports:
      - "4321:5432"
    mem_limit: 256m
    volumes:
      - ~/docker/db/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
    mem_limit: 128m

volumes:
  db:
