// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: post.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO post(
    id,
    account_id,
    is_retweet,
    picture_description,
    photo_dir
) VALUES(
    $1,$2,$3,$4,$5
) RETURNING id, account_id, picture_description, photo_dir, is_retweet, created_at
`

type CreatePostParams struct {
	ID                 uuid.UUID      `json:"id"`
	AccountID          int64          `json:"account_id"`
	IsRetweet          bool           `json:"is_retweet"`
	PictureDescription string         `json:"picture_description"`
	PhotoDir           sql.NullString `json:"photo_dir"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.AccountID,
		arg.IsRetweet,
		arg.PictureDescription,
		arg.PhotoDir,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PictureDescription,
		&i.PhotoDir,
		&i.IsRetweet,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM post
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, account_id, picture_description, photo_dir, is_retweet, created_at FROM post
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PictureDescription,
		&i.PhotoDir,
		&i.IsRetweet,
		&i.CreatedAt,
	)
	return i, err
}

const getPostQRetweetJoin = `-- name: GetPostQRetweetJoin :one
SELECT p.id,qrf.qoute_retweet  from post p
INNER JOIN qoute_retweet_feature qrf  on p.is_retweet  = qrf.qoute_retweet 
WHERE qrf.from_account_id = $2 and qrf.post_id = $1
`

type GetPostQRetweetJoinParams struct {
	PostID        uuid.UUID `json:"post_id"`
	FromAccountID int64     `json:"from_account_id"`
}

type GetPostQRetweetJoinRow struct {
	ID           uuid.UUID `json:"id"`
	QouteRetweet bool      `json:"qoute_retweet"`
}

func (q *Queries) GetPostQRetweetJoin(ctx context.Context, arg GetPostQRetweetJoinParams) (GetPostQRetweetJoinRow, error) {
	row := q.db.QueryRowContext(ctx, getPostQRetweetJoin, arg.PostID, arg.FromAccountID)
	var i GetPostQRetweetJoinRow
	err := row.Scan(&i.ID, &i.QouteRetweet)
	return i, err
}

const getPostidretweetJoin = `-- name: GetPostidretweetJoin :one
SELECT p.id,rf.retweet  from post p
INNER JOIN retweet_feature rf ON p.is_retweet  = rf.retweet 
WHERE rf.from_account_id = $2 and rf.post_id = $1
`

type GetPostidretweetJoinParams struct {
	PostID        uuid.UUID `json:"post_id"`
	FromAccountID int64     `json:"from_account_id"`
}

type GetPostidretweetJoinRow struct {
	ID      uuid.UUID `json:"id"`
	Retweet bool      `json:"retweet"`
}

func (q *Queries) GetPostidretweetJoin(ctx context.Context, arg GetPostidretweetJoinParams) (GetPostidretweetJoinRow, error) {
	row := q.db.QueryRowContext(ctx, getPostidretweetJoin, arg.PostID, arg.FromAccountID)
	var i GetPostidretweetJoinRow
	err := row.Scan(&i.ID, &i.Retweet)
	return i, err
}

const getRetweetRows = `-- name: GetRetweetRows :execrows
SELECT from_account_id, retweet, post_id, created_at, id from retweet_feature
WHERE from_account_id=$1 and post_id = $2 LIMIT 1
`

type GetRetweetRowsParams struct {
	FromAccountID int64     `json:"from_account_id"`
	PostID        uuid.UUID `json:"post_id"`
}

func (q *Queries) GetRetweetRows(ctx context.Context, arg GetRetweetRowsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, getRetweetRows, arg.FromAccountID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPost = `-- name: ListPost :many
SELECT id, account_id, picture_description, photo_dir, is_retweet, created_at FROM post
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPostParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPost(ctx context.Context, arg ListPostParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPost, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PictureDescription,
			&i.PhotoDir,
			&i.IsRetweet,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE post
SET picture_description = $2
WHERE id = $1
RETURNING id, account_id, picture_description, photo_dir, is_retweet, created_at
`

type UpdatePostParams struct {
	ID                 uuid.UUID `json:"id"`
	PictureDescription string    `json:"picture_description"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost, arg.ID, arg.PictureDescription)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PictureDescription,
		&i.PhotoDir,
		&i.IsRetweet,
		&i.CreatedAt,
	)
	return i, err
}
