// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/peacewalker122/project/service/db/repository/postgres/ent/retweet_feature"
)

// RetweetFeatureCreate is the builder for creating a Retweet_feature entity.
type RetweetFeatureCreate struct {
	config
	mutation *RetweetFeatureMutation
	hooks    []Hook
}

// SetFromAccountID sets the "from_account_id" field.
func (rfc *RetweetFeatureCreate) SetFromAccountID(i int64) *RetweetFeatureCreate {
	rfc.mutation.SetFromAccountID(i)
	return rfc
}

// SetRetweet sets the "retweet" field.
func (rfc *RetweetFeatureCreate) SetRetweet(b bool) *RetweetFeatureCreate {
	rfc.mutation.SetRetweet(b)
	return rfc
}

// SetNillableRetweet sets the "retweet" field if the given value is not nil.
func (rfc *RetweetFeatureCreate) SetNillableRetweet(b *bool) *RetweetFeatureCreate {
	if b != nil {
		rfc.SetRetweet(*b)
	}
	return rfc
}

// SetPostID sets the "post_id" field.
func (rfc *RetweetFeatureCreate) SetPostID(u uuid.UUID) *RetweetFeatureCreate {
	rfc.mutation.SetPostID(u)
	return rfc
}

// SetCreatedAt sets the "created_at" field.
func (rfc *RetweetFeatureCreate) SetCreatedAt(t time.Time) *RetweetFeatureCreate {
	rfc.mutation.SetCreatedAt(t)
	return rfc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rfc *RetweetFeatureCreate) SetNillableCreatedAt(t *time.Time) *RetweetFeatureCreate {
	if t != nil {
		rfc.SetCreatedAt(*t)
	}
	return rfc
}

// Mutation returns the RetweetFeatureMutation object of the builder.
func (rfc *RetweetFeatureCreate) Mutation() *RetweetFeatureMutation {
	return rfc.mutation
}

// Save creates the Retweet_feature in the database.
func (rfc *RetweetFeatureCreate) Save(ctx context.Context) (*Retweet_feature, error) {
	var (
		err  error
		node *Retweet_feature
	)
	rfc.defaults()
	if len(rfc.hooks) == 0 {
		if err = rfc.check(); err != nil {
			return nil, err
		}
		node, err = rfc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RetweetFeatureMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rfc.check(); err != nil {
				return nil, err
			}
			rfc.mutation = mutation
			if node, err = rfc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rfc.hooks) - 1; i >= 0; i-- {
			if rfc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rfc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rfc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Retweet_feature)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RetweetFeatureMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rfc *RetweetFeatureCreate) SaveX(ctx context.Context) *Retweet_feature {
	v, err := rfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rfc *RetweetFeatureCreate) Exec(ctx context.Context) error {
	_, err := rfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rfc *RetweetFeatureCreate) ExecX(ctx context.Context) {
	if err := rfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rfc *RetweetFeatureCreate) defaults() {
	if _, ok := rfc.mutation.Retweet(); !ok {
		v := retweet_feature.DefaultRetweet
		rfc.mutation.SetRetweet(v)
	}
	if _, ok := rfc.mutation.CreatedAt(); !ok {
		v := retweet_feature.DefaultCreatedAt
		rfc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rfc *RetweetFeatureCreate) check() error {
	if _, ok := rfc.mutation.FromAccountID(); !ok {
		return &ValidationError{Name: "from_account_id", err: errors.New(`ent: missing required field "Retweet_feature.from_account_id"`)}
	}
	if _, ok := rfc.mutation.Retweet(); !ok {
		return &ValidationError{Name: "retweet", err: errors.New(`ent: missing required field "Retweet_feature.retweet"`)}
	}
	if _, ok := rfc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "Retweet_feature.post_id"`)}
	}
	if _, ok := rfc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Retweet_feature.created_at"`)}
	}
	return nil
}

func (rfc *RetweetFeatureCreate) sqlSave(ctx context.Context) (*Retweet_feature, error) {
	_node, _spec := rfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rfc *RetweetFeatureCreate) createSpec() (*Retweet_feature, *sqlgraph.CreateSpec) {
	var (
		_node = &Retweet_feature{config: rfc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: retweet_feature.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: retweet_feature.FieldID,
			},
		}
	)
	if value, ok := rfc.mutation.FromAccountID(); ok {
		_spec.SetField(retweet_feature.FieldFromAccountID, field.TypeInt64, value)
		_node.FromAccountID = value
	}
	if value, ok := rfc.mutation.Retweet(); ok {
		_spec.SetField(retweet_feature.FieldRetweet, field.TypeBool, value)
		_node.Retweet = value
	}
	if value, ok := rfc.mutation.PostID(); ok {
		_spec.SetField(retweet_feature.FieldPostID, field.TypeUUID, value)
		_node.PostID = value
	}
	if value, ok := rfc.mutation.CreatedAt(); ok {
		_spec.SetField(retweet_feature.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RetweetFeatureCreateBulk is the builder for creating many Retweet_feature entities in bulk.
type RetweetFeatureCreateBulk struct {
	config
	builders []*RetweetFeatureCreate
}

// Save creates the Retweet_feature entities in the database.
func (rfcb *RetweetFeatureCreateBulk) Save(ctx context.Context) ([]*Retweet_feature, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rfcb.builders))
	nodes := make([]*Retweet_feature, len(rfcb.builders))
	mutators := make([]Mutator, len(rfcb.builders))
	for i := range rfcb.builders {
		func(i int, root context.Context) {
			builder := rfcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RetweetFeatureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rfcb *RetweetFeatureCreateBulk) SaveX(ctx context.Context) []*Retweet_feature {
	v, err := rfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rfcb *RetweetFeatureCreateBulk) Exec(ctx context.Context) error {
	_, err := rfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rfcb *RetweetFeatureCreateBulk) ExecX(ctx context.Context) {
	if err := rfcb.Exec(ctx); err != nil {
		panic(err)
	}
}
