// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountNotif is the predicate function for accountnotif builders.
type AccountNotif func(*sql.Selector)

// NotifRead is the predicate function for notifread builders.
type NotifRead func(*sql.Selector)

// Tokens is the predicate function for tokens builders.
type Tokens func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
