// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/peacewalker122/project/db/ent/accountnotif"
	"github.com/peacewalker122/project/db/ent/predicate"
)

// AccountNotifQuery is the builder for querying AccountNotif entities.
type AccountNotifQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AccountNotif
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccountNotifQuery builder.
func (anq *AccountNotifQuery) Where(ps ...predicate.AccountNotif) *AccountNotifQuery {
	anq.predicates = append(anq.predicates, ps...)
	return anq
}

// Limit adds a limit step to the query.
func (anq *AccountNotifQuery) Limit(limit int) *AccountNotifQuery {
	anq.limit = &limit
	return anq
}

// Offset adds an offset step to the query.
func (anq *AccountNotifQuery) Offset(offset int) *AccountNotifQuery {
	anq.offset = &offset
	return anq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (anq *AccountNotifQuery) Unique(unique bool) *AccountNotifQuery {
	anq.unique = &unique
	return anq
}

// Order adds an order step to the query.
func (anq *AccountNotifQuery) Order(o ...OrderFunc) *AccountNotifQuery {
	anq.order = append(anq.order, o...)
	return anq
}

// First returns the first AccountNotif entity from the query.
// Returns a *NotFoundError when no AccountNotif was found.
func (anq *AccountNotifQuery) First(ctx context.Context) (*AccountNotif, error) {
	nodes, err := anq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accountnotif.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (anq *AccountNotifQuery) FirstX(ctx context.Context) *AccountNotif {
	node, err := anq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccountNotif ID from the query.
// Returns a *NotFoundError when no AccountNotif ID was found.
func (anq *AccountNotifQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = anq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accountnotif.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (anq *AccountNotifQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := anq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccountNotif entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccountNotif entity is found.
// Returns a *NotFoundError when no AccountNotif entities are found.
func (anq *AccountNotifQuery) Only(ctx context.Context) (*AccountNotif, error) {
	nodes, err := anq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accountnotif.Label}
	default:
		return nil, &NotSingularError{accountnotif.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (anq *AccountNotifQuery) OnlyX(ctx context.Context) *AccountNotif {
	node, err := anq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccountNotif ID in the query.
// Returns a *NotSingularError when more than one AccountNotif ID is found.
// Returns a *NotFoundError when no entities are found.
func (anq *AccountNotifQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = anq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accountnotif.Label}
	default:
		err = &NotSingularError{accountnotif.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (anq *AccountNotifQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := anq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccountNotifs.
func (anq *AccountNotifQuery) All(ctx context.Context) ([]*AccountNotif, error) {
	if err := anq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return anq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (anq *AccountNotifQuery) AllX(ctx context.Context) []*AccountNotif {
	nodes, err := anq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccountNotif IDs.
func (anq *AccountNotifQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := anq.Select(accountnotif.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (anq *AccountNotifQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := anq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (anq *AccountNotifQuery) Count(ctx context.Context) (int, error) {
	if err := anq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return anq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (anq *AccountNotifQuery) CountX(ctx context.Context) int {
	count, err := anq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (anq *AccountNotifQuery) Exist(ctx context.Context) (bool, error) {
	if err := anq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return anq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (anq *AccountNotifQuery) ExistX(ctx context.Context) bool {
	exist, err := anq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccountNotifQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (anq *AccountNotifQuery) Clone() *AccountNotifQuery {
	if anq == nil {
		return nil
	}
	return &AccountNotifQuery{
		config:     anq.config,
		limit:      anq.limit,
		offset:     anq.offset,
		order:      append([]OrderFunc{}, anq.order...),
		predicates: append([]predicate.AccountNotif{}, anq.predicates...),
		// clone intermediate query.
		sql:    anq.sql.Clone(),
		path:   anq.path,
		unique: anq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AccountID int64 `json:"account_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccountNotif.Query().
//		GroupBy(accountnotif.FieldAccountID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (anq *AccountNotifQuery) GroupBy(field string, fields ...string) *AccountNotifGroupBy {
	grbuild := &AccountNotifGroupBy{config: anq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := anq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return anq.sqlQuery(ctx), nil
	}
	grbuild.label = accountnotif.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AccountID int64 `json:"account_id,omitempty"`
//	}
//
//	client.AccountNotif.Query().
//		Select(accountnotif.FieldAccountID).
//		Scan(ctx, &v)
func (anq *AccountNotifQuery) Select(fields ...string) *AccountNotifSelect {
	anq.fields = append(anq.fields, fields...)
	selbuild := &AccountNotifSelect{AccountNotifQuery: anq}
	selbuild.label = accountnotif.Label
	selbuild.flds, selbuild.scan = &anq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a AccountNotifSelect configured with the given aggregations.
func (anq *AccountNotifQuery) Aggregate(fns ...AggregateFunc) *AccountNotifSelect {
	return anq.Select().Aggregate(fns...)
}

func (anq *AccountNotifQuery) prepareQuery(ctx context.Context) error {
	for _, f := range anq.fields {
		if !accountnotif.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if anq.path != nil {
		prev, err := anq.path(ctx)
		if err != nil {
			return err
		}
		anq.sql = prev
	}
	return nil
}

func (anq *AccountNotifQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccountNotif, error) {
	var (
		nodes = []*AccountNotif{}
		_spec = anq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccountNotif).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccountNotif{config: anq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, anq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (anq *AccountNotifQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := anq.querySpec()
	_spec.Node.Columns = anq.fields
	if len(anq.fields) > 0 {
		_spec.Unique = anq.unique != nil && *anq.unique
	}
	return sqlgraph.CountNodes(ctx, anq.driver, _spec)
}

func (anq *AccountNotifQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := anq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (anq *AccountNotifQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accountnotif.Table,
			Columns: accountnotif.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: accountnotif.FieldID,
			},
		},
		From:   anq.sql,
		Unique: true,
	}
	if unique := anq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := anq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountnotif.FieldID)
		for i := range fields {
			if fields[i] != accountnotif.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := anq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := anq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := anq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := anq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (anq *AccountNotifQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(anq.driver.Dialect())
	t1 := builder.Table(accountnotif.Table)
	columns := anq.fields
	if len(columns) == 0 {
		columns = accountnotif.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if anq.sql != nil {
		selector = anq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if anq.unique != nil && *anq.unique {
		selector.Distinct()
	}
	for _, p := range anq.predicates {
		p(selector)
	}
	for _, p := range anq.order {
		p(selector)
	}
	if offset := anq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := anq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccountNotifGroupBy is the group-by builder for AccountNotif entities.
type AccountNotifGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (angb *AccountNotifGroupBy) Aggregate(fns ...AggregateFunc) *AccountNotifGroupBy {
	angb.fns = append(angb.fns, fns...)
	return angb
}

// Scan applies the group-by query and scans the result into the given value.
func (angb *AccountNotifGroupBy) Scan(ctx context.Context, v any) error {
	query, err := angb.path(ctx)
	if err != nil {
		return err
	}
	angb.sql = query
	return angb.sqlScan(ctx, v)
}

func (angb *AccountNotifGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range angb.fields {
		if !accountnotif.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := angb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := angb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (angb *AccountNotifGroupBy) sqlQuery() *sql.Selector {
	selector := angb.sql.Select()
	aggregation := make([]string, 0, len(angb.fns))
	for _, fn := range angb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(angb.fields)+len(angb.fns))
		for _, f := range angb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(angb.fields...)...)
}

// AccountNotifSelect is the builder for selecting fields of AccountNotif entities.
type AccountNotifSelect struct {
	*AccountNotifQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ans *AccountNotifSelect) Aggregate(fns ...AggregateFunc) *AccountNotifSelect {
	ans.fns = append(ans.fns, fns...)
	return ans
}

// Scan applies the selector query and scans the result into the given value.
func (ans *AccountNotifSelect) Scan(ctx context.Context, v any) error {
	if err := ans.prepareQuery(ctx); err != nil {
		return err
	}
	ans.sql = ans.AccountNotifQuery.sqlQuery(ctx)
	return ans.sqlScan(ctx, v)
}

func (ans *AccountNotifSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ans.fns))
	for _, fn := range ans.fns {
		aggregation = append(aggregation, fn(ans.sql))
	}
	switch n := len(*ans.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ans.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ans.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ans.sql.Query()
	if err := ans.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
