// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/peacewalker122/project/db/ent/accountnotif"
	"github.com/peacewalker122/project/db/ent/notifread"
	"github.com/peacewalker122/project/db/ent/predicate"
	"github.com/peacewalker122/project/db/ent/tokens"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAccountNotif = "AccountNotif"
	TypeNotifRead    = "NotifRead"
	TypeTokens       = "Tokens"
)

// AccountNotifMutation represents an operation that mutates the AccountNotif nodes in the graph.
type AccountNotifMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	account_id    *int64
	addaccount_id *int64
	notif_type    *string
	notif_title   *string
	notif_content *string
	notif_time    *time.Time
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*AccountNotif, error)
	predicates    []predicate.AccountNotif
}

var _ ent.Mutation = (*AccountNotifMutation)(nil)

// accountnotifOption allows management of the mutation configuration using functional options.
type accountnotifOption func(*AccountNotifMutation)

// newAccountNotifMutation creates new mutation for the AccountNotif entity.
func newAccountNotifMutation(c config, op Op, opts ...accountnotifOption) *AccountNotifMutation {
	m := &AccountNotifMutation{
		config:        c,
		op:            op,
		typ:           TypeAccountNotif,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAccountNotifID sets the ID field of the mutation.
func withAccountNotifID(id uuid.UUID) accountnotifOption {
	return func(m *AccountNotifMutation) {
		var (
			err   error
			once  sync.Once
			value *AccountNotif
		)
		m.oldValue = func(ctx context.Context) (*AccountNotif, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AccountNotif.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAccountNotif sets the old AccountNotif of the mutation.
func withAccountNotif(node *AccountNotif) accountnotifOption {
	return func(m *AccountNotifMutation) {
		m.oldValue = func(context.Context) (*AccountNotif, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AccountNotifMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AccountNotifMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AccountNotif entities.
func (m *AccountNotifMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AccountNotifMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AccountNotifMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AccountNotif.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAccountID sets the "account_id" field.
func (m *AccountNotifMutation) SetAccountID(i int64) {
	m.account_id = &i
	m.addaccount_id = nil
}

// AccountID returns the value of the "account_id" field in the mutation.
func (m *AccountNotifMutation) AccountID() (r int64, exists bool) {
	v := m.account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountID returns the old "account_id" field's value of the AccountNotif entity.
// If the AccountNotif object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountNotifMutation) OldAccountID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountID: %w", err)
	}
	return oldValue.AccountID, nil
}

// AddAccountID adds i to the "account_id" field.
func (m *AccountNotifMutation) AddAccountID(i int64) {
	if m.addaccount_id != nil {
		*m.addaccount_id += i
	} else {
		m.addaccount_id = &i
	}
}

// AddedAccountID returns the value that was added to the "account_id" field in this mutation.
func (m *AccountNotifMutation) AddedAccountID() (r int64, exists bool) {
	v := m.addaccount_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAccountID resets all changes to the "account_id" field.
func (m *AccountNotifMutation) ResetAccountID() {
	m.account_id = nil
	m.addaccount_id = nil
}

// SetNotifType sets the "notif_type" field.
func (m *AccountNotifMutation) SetNotifType(s string) {
	m.notif_type = &s
}

// NotifType returns the value of the "notif_type" field in the mutation.
func (m *AccountNotifMutation) NotifType() (r string, exists bool) {
	v := m.notif_type
	if v == nil {
		return
	}
	return *v, true
}

// OldNotifType returns the old "notif_type" field's value of the AccountNotif entity.
// If the AccountNotif object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountNotifMutation) OldNotifType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotifType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotifType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotifType: %w", err)
	}
	return oldValue.NotifType, nil
}

// ResetNotifType resets all changes to the "notif_type" field.
func (m *AccountNotifMutation) ResetNotifType() {
	m.notif_type = nil
}

// SetNotifTitle sets the "notif_title" field.
func (m *AccountNotifMutation) SetNotifTitle(s string) {
	m.notif_title = &s
}

// NotifTitle returns the value of the "notif_title" field in the mutation.
func (m *AccountNotifMutation) NotifTitle() (r string, exists bool) {
	v := m.notif_title
	if v == nil {
		return
	}
	return *v, true
}

// OldNotifTitle returns the old "notif_title" field's value of the AccountNotif entity.
// If the AccountNotif object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountNotifMutation) OldNotifTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotifTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotifTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotifTitle: %w", err)
	}
	return oldValue.NotifTitle, nil
}

// ClearNotifTitle clears the value of the "notif_title" field.
func (m *AccountNotifMutation) ClearNotifTitle() {
	m.notif_title = nil
	m.clearedFields[accountnotif.FieldNotifTitle] = struct{}{}
}

// NotifTitleCleared returns if the "notif_title" field was cleared in this mutation.
func (m *AccountNotifMutation) NotifTitleCleared() bool {
	_, ok := m.clearedFields[accountnotif.FieldNotifTitle]
	return ok
}

// ResetNotifTitle resets all changes to the "notif_title" field.
func (m *AccountNotifMutation) ResetNotifTitle() {
	m.notif_title = nil
	delete(m.clearedFields, accountnotif.FieldNotifTitle)
}

// SetNotifContent sets the "notif_content" field.
func (m *AccountNotifMutation) SetNotifContent(s string) {
	m.notif_content = &s
}

// NotifContent returns the value of the "notif_content" field in the mutation.
func (m *AccountNotifMutation) NotifContent() (r string, exists bool) {
	v := m.notif_content
	if v == nil {
		return
	}
	return *v, true
}

// OldNotifContent returns the old "notif_content" field's value of the AccountNotif entity.
// If the AccountNotif object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountNotifMutation) OldNotifContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotifContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotifContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotifContent: %w", err)
	}
	return oldValue.NotifContent, nil
}

// ClearNotifContent clears the value of the "notif_content" field.
func (m *AccountNotifMutation) ClearNotifContent() {
	m.notif_content = nil
	m.clearedFields[accountnotif.FieldNotifContent] = struct{}{}
}

// NotifContentCleared returns if the "notif_content" field was cleared in this mutation.
func (m *AccountNotifMutation) NotifContentCleared() bool {
	_, ok := m.clearedFields[accountnotif.FieldNotifContent]
	return ok
}

// ResetNotifContent resets all changes to the "notif_content" field.
func (m *AccountNotifMutation) ResetNotifContent() {
	m.notif_content = nil
	delete(m.clearedFields, accountnotif.FieldNotifContent)
}

// SetNotifTime sets the "notif_time" field.
func (m *AccountNotifMutation) SetNotifTime(t time.Time) {
	m.notif_time = &t
}

// NotifTime returns the value of the "notif_time" field in the mutation.
func (m *AccountNotifMutation) NotifTime() (r time.Time, exists bool) {
	v := m.notif_time
	if v == nil {
		return
	}
	return *v, true
}

// OldNotifTime returns the old "notif_time" field's value of the AccountNotif entity.
// If the AccountNotif object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountNotifMutation) OldNotifTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotifTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotifTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotifTime: %w", err)
	}
	return oldValue.NotifTime, nil
}

// ClearNotifTime clears the value of the "notif_time" field.
func (m *AccountNotifMutation) ClearNotifTime() {
	m.notif_time = nil
	m.clearedFields[accountnotif.FieldNotifTime] = struct{}{}
}

// NotifTimeCleared returns if the "notif_time" field was cleared in this mutation.
func (m *AccountNotifMutation) NotifTimeCleared() bool {
	_, ok := m.clearedFields[accountnotif.FieldNotifTime]
	return ok
}

// ResetNotifTime resets all changes to the "notif_time" field.
func (m *AccountNotifMutation) ResetNotifTime() {
	m.notif_time = nil
	delete(m.clearedFields, accountnotif.FieldNotifTime)
}

// SetCreatedAt sets the "created_at" field.
func (m *AccountNotifMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AccountNotifMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AccountNotif entity.
// If the AccountNotif object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AccountNotifMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AccountNotifMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the AccountNotifMutation builder.
func (m *AccountNotifMutation) Where(ps ...predicate.AccountNotif) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *AccountNotifMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (AccountNotif).
func (m *AccountNotifMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AccountNotifMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.account_id != nil {
		fields = append(fields, accountnotif.FieldAccountID)
	}
	if m.notif_type != nil {
		fields = append(fields, accountnotif.FieldNotifType)
	}
	if m.notif_title != nil {
		fields = append(fields, accountnotif.FieldNotifTitle)
	}
	if m.notif_content != nil {
		fields = append(fields, accountnotif.FieldNotifContent)
	}
	if m.notif_time != nil {
		fields = append(fields, accountnotif.FieldNotifTime)
	}
	if m.created_at != nil {
		fields = append(fields, accountnotif.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AccountNotifMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case accountnotif.FieldAccountID:
		return m.AccountID()
	case accountnotif.FieldNotifType:
		return m.NotifType()
	case accountnotif.FieldNotifTitle:
		return m.NotifTitle()
	case accountnotif.FieldNotifContent:
		return m.NotifContent()
	case accountnotif.FieldNotifTime:
		return m.NotifTime()
	case accountnotif.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AccountNotifMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case accountnotif.FieldAccountID:
		return m.OldAccountID(ctx)
	case accountnotif.FieldNotifType:
		return m.OldNotifType(ctx)
	case accountnotif.FieldNotifTitle:
		return m.OldNotifTitle(ctx)
	case accountnotif.FieldNotifContent:
		return m.OldNotifContent(ctx)
	case accountnotif.FieldNotifTime:
		return m.OldNotifTime(ctx)
	case accountnotif.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AccountNotif field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountNotifMutation) SetField(name string, value ent.Value) error {
	switch name {
	case accountnotif.FieldAccountID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountID(v)
		return nil
	case accountnotif.FieldNotifType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotifType(v)
		return nil
	case accountnotif.FieldNotifTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotifTitle(v)
		return nil
	case accountnotif.FieldNotifContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotifContent(v)
		return nil
	case accountnotif.FieldNotifTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotifTime(v)
		return nil
	case accountnotif.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AccountNotif field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AccountNotifMutation) AddedFields() []string {
	var fields []string
	if m.addaccount_id != nil {
		fields = append(fields, accountnotif.FieldAccountID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AccountNotifMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case accountnotif.FieldAccountID:
		return m.AddedAccountID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AccountNotifMutation) AddField(name string, value ent.Value) error {
	switch name {
	case accountnotif.FieldAccountID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccountID(v)
		return nil
	}
	return fmt.Errorf("unknown AccountNotif numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AccountNotifMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(accountnotif.FieldNotifTitle) {
		fields = append(fields, accountnotif.FieldNotifTitle)
	}
	if m.FieldCleared(accountnotif.FieldNotifContent) {
		fields = append(fields, accountnotif.FieldNotifContent)
	}
	if m.FieldCleared(accountnotif.FieldNotifTime) {
		fields = append(fields, accountnotif.FieldNotifTime)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AccountNotifMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AccountNotifMutation) ClearField(name string) error {
	switch name {
	case accountnotif.FieldNotifTitle:
		m.ClearNotifTitle()
		return nil
	case accountnotif.FieldNotifContent:
		m.ClearNotifContent()
		return nil
	case accountnotif.FieldNotifTime:
		m.ClearNotifTime()
		return nil
	}
	return fmt.Errorf("unknown AccountNotif nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AccountNotifMutation) ResetField(name string) error {
	switch name {
	case accountnotif.FieldAccountID:
		m.ResetAccountID()
		return nil
	case accountnotif.FieldNotifType:
		m.ResetNotifType()
		return nil
	case accountnotif.FieldNotifTitle:
		m.ResetNotifTitle()
		return nil
	case accountnotif.FieldNotifContent:
		m.ResetNotifContent()
		return nil
	case accountnotif.FieldNotifTime:
		m.ResetNotifTime()
		return nil
	case accountnotif.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown AccountNotif field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AccountNotifMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AccountNotifMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AccountNotifMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AccountNotifMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AccountNotifMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AccountNotifMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AccountNotifMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AccountNotif unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AccountNotifMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AccountNotif edge %s", name)
}

// NotifReadMutation represents an operation that mutates the NotifRead nodes in the graph.
type NotifReadMutation struct {
	config
	op            Op
	typ           string
	id            *int
	notif_id      *uuid.UUID
	account_id    *int64
	addaccount_id *int64
	read_at       *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*NotifRead, error)
	predicates    []predicate.NotifRead
}

var _ ent.Mutation = (*NotifReadMutation)(nil)

// notifreadOption allows management of the mutation configuration using functional options.
type notifreadOption func(*NotifReadMutation)

// newNotifReadMutation creates new mutation for the NotifRead entity.
func newNotifReadMutation(c config, op Op, opts ...notifreadOption) *NotifReadMutation {
	m := &NotifReadMutation{
		config:        c,
		op:            op,
		typ:           TypeNotifRead,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotifReadID sets the ID field of the mutation.
func withNotifReadID(id int) notifreadOption {
	return func(m *NotifReadMutation) {
		var (
			err   error
			once  sync.Once
			value *NotifRead
		)
		m.oldValue = func(ctx context.Context) (*NotifRead, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().NotifRead.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotifRead sets the old NotifRead of the mutation.
func withNotifRead(node *NotifRead) notifreadOption {
	return func(m *NotifReadMutation) {
		m.oldValue = func(context.Context) (*NotifRead, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotifReadMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotifReadMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotifReadMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotifReadMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().NotifRead.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNotifID sets the "notif_id" field.
func (m *NotifReadMutation) SetNotifID(u uuid.UUID) {
	m.notif_id = &u
}

// NotifID returns the value of the "notif_id" field in the mutation.
func (m *NotifReadMutation) NotifID() (r uuid.UUID, exists bool) {
	v := m.notif_id
	if v == nil {
		return
	}
	return *v, true
}

// OldNotifID returns the old "notif_id" field's value of the NotifRead entity.
// If the NotifRead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifReadMutation) OldNotifID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotifID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotifID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotifID: %w", err)
	}
	return oldValue.NotifID, nil
}

// ResetNotifID resets all changes to the "notif_id" field.
func (m *NotifReadMutation) ResetNotifID() {
	m.notif_id = nil
}

// SetAccountID sets the "account_id" field.
func (m *NotifReadMutation) SetAccountID(i int64) {
	m.account_id = &i
	m.addaccount_id = nil
}

// AccountID returns the value of the "account_id" field in the mutation.
func (m *NotifReadMutation) AccountID() (r int64, exists bool) {
	v := m.account_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountID returns the old "account_id" field's value of the NotifRead entity.
// If the NotifRead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifReadMutation) OldAccountID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountID: %w", err)
	}
	return oldValue.AccountID, nil
}

// AddAccountID adds i to the "account_id" field.
func (m *NotifReadMutation) AddAccountID(i int64) {
	if m.addaccount_id != nil {
		*m.addaccount_id += i
	} else {
		m.addaccount_id = &i
	}
}

// AddedAccountID returns the value that was added to the "account_id" field in this mutation.
func (m *NotifReadMutation) AddedAccountID() (r int64, exists bool) {
	v := m.addaccount_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAccountID resets all changes to the "account_id" field.
func (m *NotifReadMutation) ResetAccountID() {
	m.account_id = nil
	m.addaccount_id = nil
}

// SetReadAt sets the "read_at" field.
func (m *NotifReadMutation) SetReadAt(t time.Time) {
	m.read_at = &t
}

// ReadAt returns the value of the "read_at" field in the mutation.
func (m *NotifReadMutation) ReadAt() (r time.Time, exists bool) {
	v := m.read_at
	if v == nil {
		return
	}
	return *v, true
}

// OldReadAt returns the old "read_at" field's value of the NotifRead entity.
// If the NotifRead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotifReadMutation) OldReadAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReadAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReadAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReadAt: %w", err)
	}
	return oldValue.ReadAt, nil
}

// ResetReadAt resets all changes to the "read_at" field.
func (m *NotifReadMutation) ResetReadAt() {
	m.read_at = nil
}

// Where appends a list predicates to the NotifReadMutation builder.
func (m *NotifReadMutation) Where(ps ...predicate.NotifRead) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *NotifReadMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (NotifRead).
func (m *NotifReadMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotifReadMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.notif_id != nil {
		fields = append(fields, notifread.FieldNotifID)
	}
	if m.account_id != nil {
		fields = append(fields, notifread.FieldAccountID)
	}
	if m.read_at != nil {
		fields = append(fields, notifread.FieldReadAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotifReadMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notifread.FieldNotifID:
		return m.NotifID()
	case notifread.FieldAccountID:
		return m.AccountID()
	case notifread.FieldReadAt:
		return m.ReadAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotifReadMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notifread.FieldNotifID:
		return m.OldNotifID(ctx)
	case notifread.FieldAccountID:
		return m.OldAccountID(ctx)
	case notifread.FieldReadAt:
		return m.OldReadAt(ctx)
	}
	return nil, fmt.Errorf("unknown NotifRead field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotifReadMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notifread.FieldNotifID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotifID(v)
		return nil
	case notifread.FieldAccountID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountID(v)
		return nil
	case notifread.FieldReadAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReadAt(v)
		return nil
	}
	return fmt.Errorf("unknown NotifRead field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotifReadMutation) AddedFields() []string {
	var fields []string
	if m.addaccount_id != nil {
		fields = append(fields, notifread.FieldAccountID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotifReadMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case notifread.FieldAccountID:
		return m.AddedAccountID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotifReadMutation) AddField(name string, value ent.Value) error {
	switch name {
	case notifread.FieldAccountID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAccountID(v)
		return nil
	}
	return fmt.Errorf("unknown NotifRead numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotifReadMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotifReadMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotifReadMutation) ClearField(name string) error {
	return fmt.Errorf("unknown NotifRead nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotifReadMutation) ResetField(name string) error {
	switch name {
	case notifread.FieldNotifID:
		m.ResetNotifID()
		return nil
	case notifread.FieldAccountID:
		m.ResetAccountID()
		return nil
	case notifread.FieldReadAt:
		m.ResetReadAt()
		return nil
	}
	return fmt.Errorf("unknown NotifRead field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotifReadMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotifReadMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotifReadMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotifReadMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotifReadMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotifReadMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotifReadMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown NotifRead unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotifReadMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown NotifRead edge %s", name)
}

// TokensMutation represents an operation that mutates the Tokens nodes in the graph.
type TokensMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	email         *string
	access_token  *string
	refresh_token *string
	token_type    *string
	expiry        *time.Time
	raw           *map[string]interface{}
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Tokens, error)
	predicates    []predicate.Tokens
}

var _ ent.Mutation = (*TokensMutation)(nil)

// tokensOption allows management of the mutation configuration using functional options.
type tokensOption func(*TokensMutation)

// newTokensMutation creates new mutation for the Tokens entity.
func newTokensMutation(c config, op Op, opts ...tokensOption) *TokensMutation {
	m := &TokensMutation{
		config:        c,
		op:            op,
		typ:           TypeTokens,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTokensID sets the ID field of the mutation.
func withTokensID(id uuid.UUID) tokensOption {
	return func(m *TokensMutation) {
		var (
			err   error
			once  sync.Once
			value *Tokens
		)
		m.oldValue = func(ctx context.Context) (*Tokens, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Tokens.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTokens sets the old Tokens of the mutation.
func withTokens(node *Tokens) tokensOption {
	return func(m *TokensMutation) {
		m.oldValue = func(context.Context) (*Tokens, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TokensMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TokensMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Tokens entities.
func (m *TokensMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TokensMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TokensMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Tokens.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetEmail sets the "email" field.
func (m *TokensMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *TokensMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the Tokens entity.
// If the Tokens object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TokensMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *TokensMutation) ResetEmail() {
	m.email = nil
}

// SetAccessToken sets the "access_token" field.
func (m *TokensMutation) SetAccessToken(s string) {
	m.access_token = &s
}

// AccessToken returns the value of the "access_token" field in the mutation.
func (m *TokensMutation) AccessToken() (r string, exists bool) {
	v := m.access_token
	if v == nil {
		return
	}
	return *v, true
}

// OldAccessToken returns the old "access_token" field's value of the Tokens entity.
// If the Tokens object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TokensMutation) OldAccessToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccessToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccessToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccessToken: %w", err)
	}
	return oldValue.AccessToken, nil
}

// ResetAccessToken resets all changes to the "access_token" field.
func (m *TokensMutation) ResetAccessToken() {
	m.access_token = nil
}

// SetRefreshToken sets the "refresh_token" field.
func (m *TokensMutation) SetRefreshToken(s string) {
	m.refresh_token = &s
}

// RefreshToken returns the value of the "refresh_token" field in the mutation.
func (m *TokensMutation) RefreshToken() (r string, exists bool) {
	v := m.refresh_token
	if v == nil {
		return
	}
	return *v, true
}

// OldRefreshToken returns the old "refresh_token" field's value of the Tokens entity.
// If the Tokens object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TokensMutation) OldRefreshToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRefreshToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRefreshToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRefreshToken: %w", err)
	}
	return oldValue.RefreshToken, nil
}

// ResetRefreshToken resets all changes to the "refresh_token" field.
func (m *TokensMutation) ResetRefreshToken() {
	m.refresh_token = nil
}

// SetTokenType sets the "token_type" field.
func (m *TokensMutation) SetTokenType(s string) {
	m.token_type = &s
}

// TokenType returns the value of the "token_type" field in the mutation.
func (m *TokensMutation) TokenType() (r string, exists bool) {
	v := m.token_type
	if v == nil {
		return
	}
	return *v, true
}

// OldTokenType returns the old "token_type" field's value of the Tokens entity.
// If the Tokens object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TokensMutation) OldTokenType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTokenType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTokenType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTokenType: %w", err)
	}
	return oldValue.TokenType, nil
}

// ResetTokenType resets all changes to the "token_type" field.
func (m *TokensMutation) ResetTokenType() {
	m.token_type = nil
}

// SetExpiry sets the "expiry" field.
func (m *TokensMutation) SetExpiry(t time.Time) {
	m.expiry = &t
}

// Expiry returns the value of the "expiry" field in the mutation.
func (m *TokensMutation) Expiry() (r time.Time, exists bool) {
	v := m.expiry
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiry returns the old "expiry" field's value of the Tokens entity.
// If the Tokens object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TokensMutation) OldExpiry(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiry: %w", err)
	}
	return oldValue.Expiry, nil
}

// ResetExpiry resets all changes to the "expiry" field.
func (m *TokensMutation) ResetExpiry() {
	m.expiry = nil
}

// SetRaw sets the "raw" field.
func (m *TokensMutation) SetRaw(value map[string]interface{}) {
	m.raw = &value
}

// Raw returns the value of the "raw" field in the mutation.
func (m *TokensMutation) Raw() (r map[string]interface{}, exists bool) {
	v := m.raw
	if v == nil {
		return
	}
	return *v, true
}

// OldRaw returns the old "raw" field's value of the Tokens entity.
// If the Tokens object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TokensMutation) OldRaw(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRaw is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRaw requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRaw: %w", err)
	}
	return oldValue.Raw, nil
}

// ResetRaw resets all changes to the "raw" field.
func (m *TokensMutation) ResetRaw() {
	m.raw = nil
}

// Where appends a list predicates to the TokensMutation builder.
func (m *TokensMutation) Where(ps ...predicate.Tokens) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TokensMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Tokens).
func (m *TokensMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TokensMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.email != nil {
		fields = append(fields, tokens.FieldEmail)
	}
	if m.access_token != nil {
		fields = append(fields, tokens.FieldAccessToken)
	}
	if m.refresh_token != nil {
		fields = append(fields, tokens.FieldRefreshToken)
	}
	if m.token_type != nil {
		fields = append(fields, tokens.FieldTokenType)
	}
	if m.expiry != nil {
		fields = append(fields, tokens.FieldExpiry)
	}
	if m.raw != nil {
		fields = append(fields, tokens.FieldRaw)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TokensMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tokens.FieldEmail:
		return m.Email()
	case tokens.FieldAccessToken:
		return m.AccessToken()
	case tokens.FieldRefreshToken:
		return m.RefreshToken()
	case tokens.FieldTokenType:
		return m.TokenType()
	case tokens.FieldExpiry:
		return m.Expiry()
	case tokens.FieldRaw:
		return m.Raw()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TokensMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tokens.FieldEmail:
		return m.OldEmail(ctx)
	case tokens.FieldAccessToken:
		return m.OldAccessToken(ctx)
	case tokens.FieldRefreshToken:
		return m.OldRefreshToken(ctx)
	case tokens.FieldTokenType:
		return m.OldTokenType(ctx)
	case tokens.FieldExpiry:
		return m.OldExpiry(ctx)
	case tokens.FieldRaw:
		return m.OldRaw(ctx)
	}
	return nil, fmt.Errorf("unknown Tokens field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TokensMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tokens.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case tokens.FieldAccessToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccessToken(v)
		return nil
	case tokens.FieldRefreshToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRefreshToken(v)
		return nil
	case tokens.FieldTokenType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTokenType(v)
		return nil
	case tokens.FieldExpiry:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiry(v)
		return nil
	case tokens.FieldRaw:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRaw(v)
		return nil
	}
	return fmt.Errorf("unknown Tokens field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TokensMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TokensMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TokensMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Tokens numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TokensMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TokensMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TokensMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Tokens nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TokensMutation) ResetField(name string) error {
	switch name {
	case tokens.FieldEmail:
		m.ResetEmail()
		return nil
	case tokens.FieldAccessToken:
		m.ResetAccessToken()
		return nil
	case tokens.FieldRefreshToken:
		m.ResetRefreshToken()
		return nil
	case tokens.FieldTokenType:
		m.ResetTokenType()
		return nil
	case tokens.FieldExpiry:
		m.ResetExpiry()
		return nil
	case tokens.FieldRaw:
		m.ResetRaw()
		return nil
	}
	return fmt.Errorf("unknown Tokens field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TokensMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TokensMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TokensMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TokensMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TokensMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TokensMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TokensMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Tokens unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TokensMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Tokens edge %s", name)
}
